WK-master/WydarzeniaKulturalneMVC/Controllers/BiletyController.cs
using WydarzeniaKulturalne.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WydarzeniaKulturalne.Data.Entities;
using WydarzeniaKulturalne.Data;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;
using Microsoft.AspNetCore.Authorization;

namespace WydarzeniaKulturalneMVC.Controllers
{
    public class BiletyController : Controller
    {
        private readonly WydarzeniaKulturalneContext _context;
        public BiletyController(WydarzeniaKulturalneContext context)
        {
            _context = context;
        }
        public IActionResult Index(string Filtruj)
        {
            var bilety = _context.Bilety
             .Include(w => w.Wydarzenie)
             .Include(w => w.Lokalizacja)
             .ToList();

            ViewBag.Filtruj = Filtruj;
            if (Filtruj != null)
            {
                bilety = bilety.Where(f => ContainsString(f.Wydarzenie.Nazwa, Filtruj) ||
                ContainsString(f.Lokalizacja.NazwaMiejsca, Filtruj))
                    .ToList();
            }

            return View(bilety);
        }
       
        public async Task<IActionResult> DetailsCard(int? id)
        {

            var wydarzenie = await _context.Bilety
                .Include(b => b.Wydarzenie)
                .Include(b => b.Lokalizacja)
                .Where(b => b.Id == id)
                .FirstOrDefaultAsync();

            var bilety = await _context.Bilety
                .Include(b => b.Wydarzenie)
                .Include(b => b.Lokalizacja)
                .Where(b => b.WydarzenieKulturalneId == wydarzenie.WydarzenieKulturalneId)
                .OrderBy(b => b.DataWydarzenia)
                .ToListAsync();

            ViewBag.InformacjeOWydarzeniu = wydarzenie;
            ViewBag.InformacjeOWydarzeniu1 = bilety;

            var idBiletu = wydarzenie.Id;
            ViewBag.IdBiletu = idBiletu;

            return View();
        }

        public IActionResult Create()
        {
            ViewBag.LokalizacjaWydarzenia = new SelectList(_context.LokalizacjaWydarzenia, "Id", "NazwaMiejsca");
            ViewBag.WydarzenieKulturalne = new SelectList(_context.WydarzenieKulturalne, "Id", "Nazwa");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Bilety bilety)
        {
            if (ModelState.IsValid)
            {
                if (bilety.DataWydarzenia <= DateTime.Now)
                {
                    ViewBag.ErrorMessageData = "Data wydarzenia musi być datą w przyszłości.";
                    BiletyDropDownLists();
                    return View(bilety); 
                }
                if (bilety.IloscBiletow < 0)
                {
                    ViewBag.ErrorMessageLiczbaBiletow = "Liczba biletów nie może być mniejsza niż 0.";
                    BiletyDropDownLists();
                    return View(bilety); 
                }
        
                _context.Add(bilety);
                await _context.SaveChangesAsync();
                TempData["Save"] = "Pomyślnie utworzono bilet.";
                return RedirectToAction(nameof(Index));
            }


            BiletyDropDownLists();

            return View(bilety);
        }
        private void BiletyDropDownLists()
        {
            ViewBag.LokalizacjaWydarzenia = new SelectList(_context.LokalizacjaWydarzenia, "Id", "NazwaMiejsca");
            ViewBag.WydarzenieKulturalne = new SelectList(_context.WydarzenieKulturalne, "Id", "Nazwa");
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Bilety == null)
            {
                return NotFound();
            }
            var bilety = await _context.Bilety.FindAsync(id);
            if (bilety == null)
            {
                return NotFound();
            }
            ViewBag.LokalizacjaWydarzenia = new SelectList(_context.LokalizacjaWydarzenia, "Id", "NazwaMiejsca");
            ViewBag.WydarzenieKulturalne = new SelectList(_context.WydarzenieKulturalne, "Id", "Nazwa");

            return View(bilety);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Bilety bilety)
        {
            if (id != bilety.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                if (bilety.DataWydarzenia <= DateTime.Now)
                {
                    // Jeśli data wydarzenia nie jest w przyszłości, ustawia komunikat błędu.
                    ViewBag.ErrorMessageData = "Data wydarzenia musi być datą w przyszłości.";
                    BiletyDropDownLists();
                    return View(bilety);
                }
                if (bilety.IloscBiletow < 0)
                {
                    ViewBag.ErrorMessageLiczbaBiletow = "Liczba biletów nie może być mniejsza niż 0.";
                    BiletyDropDownLists();
                    return View(bilety); 
                }
                try
                {
                    _context.Update(bilety);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BiletyExists(bilety.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            BiletyDropDownLists();


            return View(bilety);
        }
        private bool BiletyExists(int id)
        {
            return (_context.Bilety?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.LokalizacjaWydarzenia == null)
            {
                return NotFound();
            }

            var bilety = await _context.Bilety
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bilety == null)
            {
                return NotFound();
            }

            return View(bilety);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Bilety == null)
            {
                return Problem("Entity set 'WydarzeniaKulturalneMVCContext.Bilety'  is null.");
            }
            var bilet = await _context.Bilety.FindAsync(id);
            if (bilet != null)
            {
                _context.Bilety.Remove(bilet);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public bool ContainsString(string source, string toCheck)
        {
            return source.IndexOf(toCheck, StringComparison.OrdinalIgnoreCase) >= 0;
        }

    }
}

WK-master/WydarzeniaKulturalneMVC/Controllers/UzytkownikController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using WydarzeniaKulturalne.Data;
using WydarzeniaKulturalne.Data.Entities;
using System.Security.Cryptography;
using System.Text;
using WydarzeniaKulturalneMVC.Models;

namespace WydarzeniaKulturalneMVC.Controllers
{
    public class UzytkownikController : Controller
    {
        private readonly WydarzeniaKulturalneContext _context;
        public UzytkownikController(WydarzeniaKulturalneContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string Filtruj)
        {

            var uzytkownik = _context.Uzytkownik.Include(u => u.Rola).ToList();

            ViewBag.Filtruj = Filtruj;

            if (Filtruj != null)
                uzytkownik = uzytkownik.Where(f => ContainsString(f.Imie, Filtruj) ||
                ContainsString(f.Nazwisko, Filtruj) ||
                ContainsString (f.Rola.Nazwa, Filtruj)               
                ).ToList();
       

            return View(uzytkownik);

        }
        public IActionResult Rejestracja()
        {
            return View("Rejestracja");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            HttpContext.Session.Clear();

            return Redirect("/");

        }
        public IActionResult Logowanie()
        {
            return View("Logowanie");
        }
        [HttpPost]
        public async Task<IActionResult> Logowanie(string Email, string Haslo)
        {
           
            if (string.IsNullOrWhiteSpace(Email) || string.IsNullOrWhiteSpace(Haslo))
            {
                ViewBag.ErrorMessageLogin = "Email i hasło są wymagane.";
                return View("Logowanie");
            }

            var uzytkownik = await _context.Uzytkownik.Include(x => x.Rola).FirstOrDefaultAsync(x => x.Email == Email);

            if (uzytkownik == null)
            {
                ViewBag.ErrorMessageLogin = "Użytkownik o podanym adresie email nie istnieje.";
                return View("Logowanie");
            }

            if (uzytkownik.Haslo == hashPassword(Haslo))
            {
                ClaimsPrincipal rezultat = new ClaimsPrincipal();

                var claims = new List<Claim>
        {
            new Claim(ClaimTypes.Email, uzytkownik.Email),
            new Claim(ClaimTypes.Name, uzytkownik.Email),
            new Claim(ClaimTypes.Role, uzytkownik.Rola.Nazwa),
            new Claim(ClaimTypes.NameIdentifier, uzytkownik.Id.ToString()),
        };

                var koszyk = new Koszyk(_context, this.HttpContext);

                var claimsIdentity = new ClaimsIdentity(
                    claims, CookieAuthenticationDefaults.AuthenticationScheme);
  
                var authProperties = new AuthenticationProperties
                {
                    ExpiresUtc = DateTime.Now.AddMinutes(30),
                };

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(new ClaimsIdentity(claimsIdentity)));
                if (uzytkownik.Rola?.Nazwa == "Admin")
                {
                    return RedirectToAction("AdminPanel", "Home");
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                ViewBag.ErrorMessageLogin = "Mail lub hasło jest niepoprawne.";
                return View("Logowanie");
            }
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Uzytkownik == null)
            {
                return NotFound();
            }

            var uzytkownik = await _context.Uzytkownik
                .FirstOrDefaultAsync(m => m.Id == id);
            if (uzytkownik == null)
            {
                return NotFound();
            }
          
            return View(uzytkownik);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Uzytkownik uzytkownik, string weryfikujHaslo)
        {
            // Check for empty email or password
            if (string.IsNullOrWhiteSpace(uzytkownik.Email) || string.IsNullOrWhiteSpace(uzytkownik.Haslo))
            {
                ViewBag.EmailErrorMessage = "Podaj adres email i hasło. Pole nie może być puste.";
                return View("Rejestracja");
            }
            if (string.IsNullOrWhiteSpace(uzytkownik.Imie) || string.IsNullOrWhiteSpace(uzytkownik.Nazwisko))
            {
                ViewBag.DaneErrorMessage = "Pole nie może być puste.";
                return View("Rejestracja");
            }

            if (uzytkownik.Email.Contains(" ") || uzytkownik.Haslo.Contains(" "))
            {
                ViewBag.EmailErrorMessage = "Adres email i hasło nie mogą zawierać spacji.";
                return View("Rejestracja");
            }

            var nowyUzytkownik = await _context.Uzytkownik.FirstOrDefaultAsync(u => u.Email == uzytkownik.Email);
            if (nowyUzytkownik != null)
            {
                ViewBag.EmailErrorMessage = "Email w użyciu. Proszę wybrać inny.";
                return View("Rejestracja");
            }

            if (hashPassword(uzytkownik.Haslo) != hashPassword(weryfikujHaslo))
            {
                ViewBag.PasswordErrorMessage = "Hasła różnią się od siebie. Zweryfikuj wpisane dane";
                return View("Rejestracja");
            }

                if (hashPassword(uzytkownik.Haslo) == hashPassword(weryfikujHaslo))
            {
                if (nowyUzytkownik == null)
                {
                    if (ModelState.IsValid)
                    {
                        uzytkownik.Haslo = hashPassword(uzytkownik.Haslo);
                        _context.Add(uzytkownik);

                        await _context.SaveChangesAsync();


                        ViewBag.LoginMessage = "Konto zostało pomyślnie utworzone";
                        TempData["Save"] = "Pomyślnie utworzono nowy obiekt";
                        return View("Logowanie");
                    }

                    return View("Rejestracja");
                }
            }

            ViewBag.PasswordErrorMessage = "Podane hasła różnią się od siebie.";
            return View("Rejestracja");
        }

        string hashPassword(string password)
        {
            var sha = SHA512.Create();
            var asByteArray = Encoding.Default.GetBytes(password);
            var hashedPassword = sha.ComputeHash(asByteArray);
            return Convert.ToBase64String(hashedPassword);
        }
        public bool ContainsString(string source, string toCheck)
        {
            return source.IndexOf(toCheck, StringComparison.OrdinalIgnoreCase) >= 0;
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var uzytkownik = await _context.Uzytkownik.FindAsync(id);
            if (uzytkownik == null)
            {
                return NotFound();
            }
            return View(uzytkownik);
        }

        // UPDATE: POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Imie,Nazwisko,Haslo,Email,RolaId")] Uzytkownik uzytkownik)
        {
            if (id != uzytkownik.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Update(uzytkownik);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(uzytkownik);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var uzytkownik = await _context.Uzytkownik
                .FirstOrDefaultAsync(m => m.Id == id);
            if (uzytkownik == null)
            {
                return NotFound();
            }

            return View(uzytkownik);
        }

        // DELETE: POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var uzytkownik = await _context.Uzytkownik.FindAsync(id);
            _context.Uzytkownik.Remove(uzytkownik);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
   

}

//Edycja danych uzyutkownika ?
//Edycja hasla uzytkownika/? 

WK-master/WydarzeniaKulturalneMVC/Views/Bilety/Create.cshtml
@model WydarzeniaKulturalne.Data.Entities.Bilety

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card shadow m-4 p-4">
    <h4 class="ml-3 mb-3 py-3"> Bilety</h4>

    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <form enctype="multipart/form-data" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <a asp-action="Index" class="btn btn-warning">Powrót</a>
                    <input type="submit" value="Zapisz" class="btn btn-primary" />
                </div>


                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="WydarzenieKulturalneId" class="control-label">Wydarzenie</label>
                            <select asp-for="WydarzenieKulturalneId" class="form-control" asp-items="ViewBag.WydarzenieKulturalne"></select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="LokalizacjaWydarzeniaId" class="control-label">Lokalizacja</label>
                            <select asp-for="LokalizacjaWydarzeniaId" class="form-control" asp-items="ViewBag.LokalizacjaWydarzenia"></select>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label asp-for="IloscBiletow" class="control-label"></label>
                            <input asp-for="IloscBiletow" class="form-control" />
                            <span asp-validation-for="IloscBiletow" class="text-danger"></span>
                            <p style="color: darkred">@ViewBag.ErrorMessageLiczbaBiletow</p>
                      
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="form-group">
                            <label asp-for="Marza" class="control-label">Marża %</label>
                            <input asp-for="Marza" class="form-control"/><p></p>
                            <span asp-validation-for="Marza" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="DataWydarzenia" class="control-label"></label>
                            <input asp-for="DataWydarzenia" class="form-control" />
                            <span asp-validation-for="DataWydarzenia" class="text-danger"></span>
                            <p style="color: darkred">@ViewBag.ErrorMessageData</p>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="CzyDostepne" type="checkbox" checked/> @Html.DisplayNameFor(model => model.CzyDostepne)
                            </label>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        tinymce.init({
            forced_root_block: "",
            selector: 'textarea',
            menubar: false,
            statusbar: false,
            language: 'pl'
        });
    </script>
    }

WK-master/WydarzeniaKulturalneMVC/Views/Bilety/Delete.cshtml
@model WydarzeniaKulturalne.Data.Entities.Bilety

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card shadow m-4 p-4">
    <h4 class="ml-3 mb-3 py-3"> Usuwanie</h4>

    <div class="row">
        <div class="col-lg-8 offset-lg-2 ">

            <h3>Czy jesteś pewien, że chcesz usunąć ten obiekt?</h3>
            <div class="mt-4 mb-4">
                <form asp-action="Delete">
                    <input type="hidden" asp-for="Id" />
                    <a asp-action="Index" class="btn btn-warning">Powrót</a>
                    <input type="submit" value="Usuń" class="btn btn-danger" />
                </form>
            </div>
        </div>
    </div>
</div>

WK-master/WydarzeniaKulturalneMVC/Views/Bilety/DetailsCard.cshtml
@model IEnumerable<WydarzeniaKulturalne.Data.Entities.Bilety>
@{
    ViewData["Title"] = "DetailsCard";
    var wydarzenie = (WydarzeniaKulturalne.Data.Entities.Bilety)ViewBag.InformacjeOWydarzeniu;
    var idBiletu = ViewBag.IdBiletu;
    
}
<style>

    .nameDetails {
        display: inline-block
    }

    .bg-details {
        background-color: none;
        border-radius: 8px
    }

        .bg-details:hover {
            background-color: #f8fafb;
            color: #08183a;
            cursor: pointer;
        }

            .bg-details:hover .fa-check,
            .bg-details:hover .fa-minus {
                background-color: #f8fafb;
                color: #08183a;
            }

    .btn-details-header {
        background-color: transparent;
        color: #08183a;
        box-shadow: none;
        cursor: pointer;
    }

        .btn-details-header:hover {
            background-color: #f8fafb;
            color: #de753f;
            cursor: pointer;
            box-shadow: none;
        }

    .table-details thead th,
    .table-details td {
        border: none
    }

    .table-details tbody td:first-child {
        border-bottom-left-radius: 10px;
        border-top-left-radius: 10px
    }

    .table-details tbody td:last-child {
        border-bottom-right-radius: 10px;
        border-top-right-radius: 10px
    }

    .h5-detail {
        text-transform: uppercase;
        color: #de753f;
    }

    #spacing-row-details {
        height: 9px;
    }
</style>
<main class="mt-2 pt-4">
    <div class="container mt-2">
        <div class="row">
        </div>
        <hr />
        <!--Grid row-->
        <div class="row">
            <!--Grid column-->
            <div class="col-md-6 mb-4 " style="width: 20rem;">

                @if (string.IsNullOrEmpty(wydarzenie.Wydarzenie?.ZdjecieUrl))
                {
                    <img src="~/Zdjecia/noimage.png" class="img-fluid" />
                }
                else
                {
                    <img src="@wydarzenie.Wydarzenie?.ZdjecieUrl" class="img-fluid" alt="" />
                }
            </div>

            <div class="col-md-6 mb-4">
                <!--Content-->
                <div class="p-4">
                    <div class="mb-3">

                        @if (@wydarzenie.Wydarzenie?.Promowane == true)
                        {
                            <span class="badge bg-info me-1">Promowane</span>
                        }
                    </div>

                    <strong><p style="font-size: 20px;">@wydarzenie.Wydarzenie?.Nazwa</p></strong>
                    <p>@Html.Raw(@wydarzenie.Wydarzenie?.Opis)</p>
                </div>
            </div>
        </div>
        <hr />
        <div class="container rounded mt-3 bg-white p-md-4">
            <div class="h5-detail m-3 mb-3">
                Dostępne wydarzenia
                @*               <div class="dropdown float-end mb-3">
                <button class="btn btn-dark btn-details-header dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                Lokalizacja
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
                </div>*@
            </div>
            <div class="table-responsive w-100">
                <table class="table table-details">
                    <thead>
                        <tr>
                            <th scope="col">Data</th>
                            <th scope="col">Miejsce</th>
                            <th scope="col"></th>
                         @*   <th scope="col">Status</th>*@
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var bilet in ViewBag.InformacjeOWydarzeniu1)
                        {
                            var sumaCena = bilet.Wydarzenie.Cena+(bilet.Wydarzenie.Cena * bilet.Marza)/100;
                            <tr class="bg-details">
                                <td class="pt-3 mt-1">
                                    @bilet.DataWydarzenia.ToString("yyyy-MM-dd") <br />
                                    @bilet.DataWydarzenia.ToString(" HH:mm")
                                </td>
                                <td class="pt-3 mt-1">
                                    <div class="pl-lg-5 pl-md-3 pl-1 nameDetails">
                                        @bilet.Lokalizacja?.Miejscowosc
                                        <br>
                                        @bilet.Lokalizacja?.NazwaMiejsca
                                    </div>
                                </td>

                                <td class="pt-3 mt-1">
                                    Dotępne bilety: @bilet.IloscBiletow
                                    <br>
                                    Cena: @sumaCena.ToString("C")
                                </td>
                                @if (@bilet.IloscBiletow > 0)
                                {
                                  @*  <td class="pt-3 mt-1"><span class="fa fa-check pl-3"></span></td>*@
                                    <td class="pt-3 mt-2">

                                        @if (User.Identity.IsAuthenticated)
                                        {
                                            <a asp-controller="Koszyk" asp-action="DodajDoKoszyka" asp-route-id="@bilet.Id" class="btn btn-dark">
                                                Kup bilet
                                            </a>
                                        }
                                        else
                                        {
                                            <p>Zaloguj się, aby dodać bilet do koszyka.</p>
                                            <a asp-controller="Uzytkownik" asp-action="Logowanie" class="btn btn-primary">
                                                Zaloguj się
                                            </a>
                                        }
                                    </td>
                                }
                                else
                                {
                                    <td class="pt-3 mt-2">
                                        <a class="btn btn-grey" disabled>
                                         Wyprzedane
                                        </a>
                                    </td>
                                }

                               @* <a asp-controller="Koszyk" asp-action="DodajDoKoszyka" asp-route-id="@idBiletu" class="btn btn-dark">
                                    Kup bilet
                                </a>*@
                            </tr>

                            <tr id="spacing-row">
                                <td></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>