WK-master/WydarzeniaKulturalneMVC/Controllers/BiletyController.cs
using WydarzeniaKulturalne.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WydarzeniaKulturalne.Data.Entities;
using WydarzeniaKulturalne.Data;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;
using Microsoft.AspNetCore.Authorization;

namespace WydarzeniaKulturalneMVC.Controllers
{
    public class BiletyController : Controller
    {
        private readonly WydarzeniaKulturalneContext _context;
        public BiletyController(WydarzeniaKulturalneContext context)
        {
            _context = context;
        }
        public IActionResult Index(string Filtruj)
        {
            var bilety = _context.Bilety
             .Include(w => w.Wydarzenie)
             .Include(w => w.Lokalizacja)
             .ToList();

            ViewBag.Filtruj = Filtruj;
            if (Filtruj != null)
            {
                bilety = bilety.Where(f => ContainsString(f.Wydarzenie.Nazwa, Filtruj) ||
                ContainsString(f.Lokalizacja.NazwaMiejsca, Filtruj))
                    .ToList();
            }

            return View(bilety);
        }
       
        public async Task<IActionResult> DetailsCard(int? id)
        {

            var wydarzenie = await _context.Bilety
                .Include(b => b.Wydarzenie)
                .Include(b => b.Lokalizacja)
                .Where(b => b.Id == id)
                .FirstOrDefaultAsync();

            var bilety = await _context.Bilety
                .Include(b => b.Wydarzenie)
                .Include(b => b.Lokalizacja)
                .Where(b => b.WydarzenieKulturalneId == wydarzenie.WydarzenieKulturalneId)
                .OrderBy(b => b.DataWydarzenia)
                .ToListAsync();

            ViewBag.InformacjeOWydarzeniu = wydarzenie;
            ViewBag.InformacjeOWydarzeniu1 = bilety;

            var idBiletu = wydarzenie.Id;
            ViewBag.IdBiletu = idBiletu;

            return View();
        }

        public IActionResult Create()
        {
            ViewBag.LokalizacjaWydarzenia = new SelectList(_context.LokalizacjaWydarzenia, "Id", "NazwaMiejsca");
            ViewBag.WydarzenieKulturalne = new SelectList(_context.WydarzenieKulturalne, "Id", "Nazwa");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Bilety bilety)
        {
            if (ModelState.IsValid)
            {
                if (bilety.DataWydarzenia <= DateTime.Now)
                {
                    ViewBag.ErrorMessageData = "Data wydarzenia musi być datą w przyszłości.";
                    BiletyDropDownLists();
                    return View(bilety); 
                }
                if (bilety.IloscBiletow < 0)
                {
                    ViewBag.ErrorMessageLiczbaBiletow = "Liczba biletów nie może być mniejsza niż 0.";
                    BiletyDropDownLists();
                    return View(bilety); 
                }
        
                _context.Add(bilety);
                await _context.SaveChangesAsync();
                TempData["Save"] = "Pomyślnie utworzono bilet.";
                return RedirectToAction(nameof(Index));
            }


            BiletyDropDownLists();

            return View(bilety);
        }
        private void BiletyDropDownLists()
        {
            ViewBag.LokalizacjaWydarzenia = new SelectList(_context.LokalizacjaWydarzenia, "Id", "NazwaMiejsca");
            ViewBag.WydarzenieKulturalne = new SelectList(_context.WydarzenieKulturalne, "Id", "Nazwa");
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Bilety == null)
            {
                return NotFound();
            }
            var bilety = await _context.Bilety.FindAsync(id);
            if (bilety == null)
            {
                return NotFound();
            }
            ViewBag.LokalizacjaWydarzenia = new SelectList(_context.LokalizacjaWydarzenia, "Id", "NazwaMiejsca");
            ViewBag.WydarzenieKulturalne = new SelectList(_context.WydarzenieKulturalne, "Id", "Nazwa");

            return View(bilety);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Bilety bilety)
        {
            if (id != bilety.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                if (bilety.DataWydarzenia <= DateTime.Now)
                {
                    // Jeśli data wydarzenia nie jest w przyszłości, ustawia komunikat błędu.
                    ViewBag.ErrorMessageData = "Data wydarzenia musi być datą w przyszłości.";
                    BiletyDropDownLists();
                    return View(bilety);
                }
                if (bilety.IloscBiletow < 0)
                {
                    ViewBag.ErrorMessageLiczbaBiletow = "Liczba biletów nie może być mniejsza niż 0.";
                    BiletyDropDownLists();
                    return View(bilety); 
                }
                try
                {
                    _context.Update(bilety);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BiletyExists(bilety.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            BiletyDropDownLists();


            return View(bilety);
        }
        private bool BiletyExists(int id)
        {
            return (_context.Bilety?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.LokalizacjaWydarzenia == null)
            {
                return NotFound();
            }

            var bilety = await _context.Bilety
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bilety == null)
            {
                return NotFound();
            }

            return View(bilety);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Bilety == null)
            {
                return Problem("Entity set 'WydarzeniaKulturalneMVCContext.Bilety'  is null.");
            }
            var bilet = await _context.Bilety.FindAsync(id);
            if (bilet != null)
            {
                _context.Bilety.Remove(bilet);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public bool ContainsString(string source, string toCheck)
        {
            return source.IndexOf(toCheck, StringComparison.OrdinalIgnoreCase) >= 0;
        }

    }
}

WK-master/WydarzeniaKulturalneMVC/Controllers/FinalizacjaKoszykController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using WydarzeniaKulturalne.Data;
using WydarzeniaKulturalne.Data.Entities;
using WydarzeniaKulturalneMVC.Models;
using WydarzeniaKulturalneMVC.ViewModel;
namespace WydarzeniaKulturalneMVC.Controllers
{
    //[Authorize]
    public class FinalizacjaKoszykaController : Controller
    {

        private readonly WydarzeniaKulturalneContext _context;
        string kodPromocyjny;
        private Koszyk _koszyk;

        public FinalizacjaKoszykaController(WydarzeniaKulturalneContext context, IHttpContextAccessor httpContextAccessor)
        {
            _koszyk = new Koszyk(context, httpContextAccessor.HttpContext);
            _context = context;
        }

        public async Task<IActionResult> Index(string Filtruj)
        {

            var zamowienieSzczegolyQuery = _context.ZamowienieSzczegoly
                 .Join(_context.Zamowienie,
                     szczegol => szczegol.IdZamowienie,
                     zamowienie => zamowienie.IdZamowienie,
                     (szczegol, zamowienie) => new { Szczegol = szczegol, Zamowienie = zamowienie })
                 .Join(_context.Bilety,
                     szczegolZamowienie => szczegolZamowienie.Szczegol.IdBilet,
                     bilet => bilet.Id,
                     (szczegolZamowienie, bilet) => new { SzczegolZamowienie = szczegolZamowienie, Bilet = bilet })
                 .OrderByDescending(x => x.SzczegolZamowienie.Szczegol.IdZamowienie)
                 .Select(x => new
                 {
                     IdZamowienieSzczegoly = x.SzczegolZamowienie.Szczegol.IdZamowienieSzczegoly,
                     IdZamowienie = x.SzczegolZamowienie.Szczegol.IdZamowienie,
                     IdBilet = x.SzczegolZamowienie.Szczegol.IdBilet,
                     Ilosc = x.SzczegolZamowienie.Szczegol.Ilosc,
                     Cena = x.SzczegolZamowienie.Szczegol.Cena,
                     Marza = x.Bilet.Marza,
                     NazwaBiletu = x.Bilet.Wydarzenie.Nazwa,
                     DataWydarzenia = x.Bilet.DataWydarzenia,
                     ZdjecieUrl = x.Bilet.Wydarzenie.ZdjecieUrl,
                     Miejscowosc = x.Bilet.Lokalizacja.Miejscowosc,
                     NazwaLokalizacji = x.Bilet.Lokalizacja.NazwaMiejsca
                 });

            if (!string.IsNullOrEmpty(Filtruj))
            {
                zamowienieSzczegolyQuery = zamowienieSzczegolyQuery
                    .Where(x => x.IdZamowienie.ToString().Equals(Filtruj));
            }

            var zamowienieSzczegolyList = await zamowienieSzczegolyQuery.ToListAsync();

            ViewBag.Filtruj = Filtruj;
            ViewBag.SprzedaneBilety = zamowienieSzczegolyList;

            return View(zamowienieSzczegolyList);
        }

        public IActionResult Platnosc()
        {
            var idSesjiKoszyka = _koszyk.IdSesjiKoszyka;
            decimal sumaZamowienia = _context.ElementKoszyka
                                  .Include(b => b.Bilety)
                                 .Where(e => e.IdSesjiKoszyka == idSesjiKoszyka)
                                 .Sum(item => (item.Bilety.Wydarzenie.Cena + ((item.Bilety.Wydarzenie.Cena * item.Bilety.Marza)) / 100) * item.Ilosc);

            ViewBag.SumaZamowienia = sumaZamowienia;

            return View();
        }
        [HttpPost]
        public IActionResult Platnosc(Zamowienie zamowienie, string kodPromocyjnyWpis)
        {
            var idSesjiKoszyka = _koszyk.IdSesjiKoszyka;
            int uzytkownikId = 0;
            var uzytkownikIdClaim = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
            if (uzytkownikIdClaim != null && int.TryParse(uzytkownikIdClaim, out var parsedId))
            {
                uzytkownikId = parsedId;
            }

            var koszykElementy = _context.ElementKoszyka
                                 .Include(e => e.Bilety)
                                 .Include(e => e.Bilety.Wydarzenie)
                                 .Where(e => e.IdSesjiKoszyka == idSesjiKoszyka).ToList();

            decimal sumaZamowienia = _context.ElementKoszyka
                                            .Include(b => b.Bilety)
                                           .Where(e => e.IdSesjiKoszyka == idSesjiKoszyka)
                                           .Sum(item => (item.Bilety.Wydarzenie.Cena + item.Bilety.Marza) * item.Ilosc);

            ViewBag.SumaZamowienia = sumaZamowienia;
            var order = new Zamowienie
            {

                Imie = zamowienie.Imie,
                Nazwisko = zamowienie.Nazwisko,
                Email = User.Identity.Name,
                UzytkownikId = uzytkownikId, // Ustawienie UzytkownikId
                OrderDate = DateTime.Now,
                Suma = sumaZamowienia

            };

            kodPromocyjny = "WSB";

            if (string.Equals(kodPromocyjny, kodPromocyjnyWpis, StringComparison.OrdinalIgnoreCase) == false)
            {
                TempData["ErrorMessagePlatnosc"] = "Błędny kod promocji. Jedyny właściwy to: WSB";
                return View(order);
            }
            try
            {
                // Zapisz zamówienie
                _context.Zamowienie.Add(order);
                _context.SaveChanges();

                // Pobierz elementy koszyka dla zalogowanego użytkownika
                var zalogowanyUzytkownikKoszyk = _context.ElementKoszyka
                        .Where(c => c.IdSesjiKoszyka == idSesjiKoszyka)
                        .Include(c => c.Bilety)
                        .Include(c => c.Bilety.Wydarzenie)
                        .ToList();

                // Przypisz elementy koszyka do zamówienia
                foreach (var cartItem in zalogowanyUzytkownikKoszyk)
                {
                    var szczegolZamowienia = new ZamowienieSzczegoly
                    {
                        IdZamowienie = order.IdZamowienie,
                        IdBilet = cartItem.IdBilet,
                        Ilosc = cartItem.Ilosc,
                        Cena = cartItem.Bilety.Wydarzenie.Cena
                    };
                    _context.ZamowienieSzczegoly.Add(szczegolZamowienia);

                }

                _context.ElementKoszyka.RemoveRange(zalogowanyUzytkownikKoszyk);
                _context.SaveChanges();
            }
            catch (Exception ex)
            {

                ViewBag.ErrorMessage = "Wystąpił problem podczas przetwarzania zamówienia. Spróbuj ponownie.";
                return View(zamowienie);
            }

            return RedirectToAction("Zakoncz", new { id = order.IdZamowienie });

        }

        public IActionResult Zakoncz(int id)
        {
            return View(id);

        }
        public IActionResult ListaSzczegolowZamowienPoEmail()
        {
            var userEmail = User.Identity.Name;

            if (string.IsNullOrEmpty(userEmail))
            {
                return View(new List<ZamowienieSzczegoly>());
            }

            var zamowienieSzczegolyList = _context.ZamowienieSzczegoly
             .Join(_context.Zamowienie,
                 szczegol => szczegol.IdZamowienie,
                 zamowienie => zamowienie.IdZamowienie,
                 (szczegol, zamowienie) => new { Szczegol = szczegol, Zamowienie = zamowienie })
             .Join(_context.Bilety,
                 szczegolZamowienie => szczegolZamowienie.Szczegol.IdBilet,
                 bilet => bilet.Id,
                 (szczegolZamowienie, bilet) => new { SzczegolZamowienie = szczegolZamowienie, Bilet = bilet })
             .Where(x => x.SzczegolZamowienie.Zamowienie.Email == userEmail)
             .OrderByDescending(x => x.SzczegolZamowienie.Szczegol.IdZamowienie)
             .Select(x => new
             {
                 IdZamowienieSzczegoly = x.SzczegolZamowienie.Szczegol.IdZamowienieSzczegoly,
                 IdZamowienie = x.SzczegolZamowienie.Szczegol.IdZamowienie,
                 IdBilet = x.SzczegolZamowienie.Szczegol.IdBilet,
                 Ilosc = x.SzczegolZamowienie.Szczegol.Ilosc,
                 Cena = x.SzczegolZamowienie.Szczegol.Cena,
                 Marza = x.Bilet.Marza,
                 NazwaBiletu = x.Bilet.Wydarzenie.Nazwa,
                 DataWydarzenia = x.Bilet.DataWydarzenia,
                 ZdjecieUrl = x.Bilet.Wydarzenie.ZdjecieUrl,
                 Miejscowosc = x.Bilet.Lokalizacja.Miejscowosc,
                 NazwaLokalizacji = x.Bilet.Lokalizacja.NazwaMiejsca
             })
             .ToList();

            return View(zamowienieSzczegolyList);
        }

        public IActionResult StatystykaSprzedazy(DateTime? dataWydarzeniaOd, DateTime? dataWydarzeniaDo)
        {


            var wynik = (from zamowienieSzczegoly in _context.ZamowienieSzczegoly
                         join bilet in _context.Bilety on zamowienieSzczegoly.IdBilet equals bilet.Id
                         join zamowienie in _context.Zamowienie on zamowienieSzczegoly.IdZamowienie equals zamowienie.IdZamowienie
                         group zamowienieSzczegoly by new { bilet.Wydarzenie.Nazwa, bilet.Wydarzenie.ZdjecieUrl, bilet.Lokalizacja.Miejscowosc, bilet.Lokalizacja.NazwaMiejsca, bilet.Marza } into grupowaneBilety
                         select new
                         {
                             NazwaWydarzenia = grupowaneBilety.Key.Nazwa,
                             ZdjecieUrl = grupowaneBilety.Key.ZdjecieUrl,
                             MiejsceWydarzenia = grupowaneBilety.Key.Miejscowosc,
                             NazwaMiejsca = grupowaneBilety.Key.NazwaMiejsca,
                             LacznaIlosc = grupowaneBilety.Sum(gb => gb.Ilosc),
                             ZyskZMarzy = grupowaneBilety.Sum(gb => gb.Ilosc * gb.Cena * grupowaneBilety.Key.Marza / 100),

WK-master/WydarzeniaKulturalneMVC/Views/Koszyk/Index.cshtml
@model WydarzeniaKulturalneMVC.Models.DaneKoszyk

@{
    ViewData["Title"] = "Index";
}

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $(".Usuwanie").click(function () {
            var recordToDelete = $(this).data("id");
            if (recordToDelete !== '') {
                $.ajax({
                    url: "/Koszyk/UsunZKoszyka",
                    type: "POST",
                    data: { "id": recordToDelete },
                    success: function (data) {
                        location.reload(true);
                    }
                });
            }
        });
    });
</script>
<main class="mt-5 pt-4">
    <section>
        <div class="container py-5 ">
            <div class="row d-flex justify-content-center align-items-center">
                <div class="col-12 mb-5">
                    <div class="card-shop">
                        <div class="card-body p-0">
                            <div class="row g-0">
                                <div class="col-lg-8">
                                    <div class="p-5">
                                        <div class="d-flex justify-content-between align-items-center">
                                            <strong><p style="font-size: 20px;">Koszyk</p></strong>
                                            <h6 class="mb-0 text-muted">
                                                Łacznie biletów:
                                                @Model.IloscBiletow
                                            </h6>
                                        </div>
                                        <hr class="my-4">
                                        @if (Model.ElementyKoszyka != null && Model.ElementyKoszyka.Any())
                                        { 

                                            @foreach (var item in Model.ElementyKoszyka)
                                            {
                                         
                                                var sumaBilet = item.Bilety.Wydarzenie.Cena + (item.Bilety.Wydarzenie.Cena * item.Bilety.Marza)/100;
                                                <div class="row mb-4 d-flex justify-content-between align-items-center">
                                                    <div class="col-md-2 col-lg-2 col-xl-2">
                                                        @if (string.IsNullOrEmpty(@item.Bilety?.Wydarzenie?.ZdjecieUrl))
                                                        {
                                                            <a asp-controller="Bilety" asp-action="DetailsCard" asp-route-id="@item.IdBilet">
                                                                <img src="~/Zdjecia/noimage.png" class="img-fluid rounded-3" />
                                                            </a>
                                                        }
                                                        else
                                                        {
                                                            <a asp-controller="Bilety" asp-action="DetailsCard" asp-route-id="@item.IdBilet">
                                                                <img src="@item.Bilety?.Wydarzenie.ZdjecieUrl" class="img-fluid rounded-3" />
                                                            </a>
                                                        }

                                                    </div>
                                                    <div class="col-md-3 col-lg-3 col-xl-3">
                                                        <h6 class="text-muted">@item.Bilety?.Wydarzenie?.Nazwa</h6>
                                                        <h6 class="text-black mb-2">@item.Bilety?.Lokalizacja?.NazwaMiejsca</h6>
                                                        <h6 class="text-black mb-2 small">@item.Bilety?.Lokalizacja?.Miejscowosc</h6>
                                                        <h6 class="text-black mt-2 small">@item.Bilety?.DataWydarzenia.ToString("yyyy-MM-dd")</h6>
                                                    </div>
                                                    <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                                                        <a href="#" class="Usuwanie" data-id="@item.IdElementuKoszyka">
                                                            <i class="fas fa-minus" style="margin-right: 1rem;"></i>
                                                        </a>
                                                        @item.Ilosc
                                                    </div>
                                                   
                                                    <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                                        <h6 class="mb-0">@sumaBilet.ToString("C")</h6>
                                                    </div>
                                                    <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                                                        <a href="#!" class="text-muted"><i class="fas fa-times"></i></a>
                                                    </div>
                                                </div>
                                            }
                                        }
                                        else
                                        {
                                            <div class="alert alert-warning" role="alert">
                                                Obecnie brak biletów w koszyku.
                                            </div>
                                        }

                                        <div class="pt-5">
                                            <h6 class="mb-0">
                                                <a asp-controller="Home" asp-action="Index" class="text-body">
                                                    <i class="fas fa-long-arrow-alt-left me-2"></i>Powrót
                                                </a>
                                            </h6>
                                        </div>
                                    </div>
                                </div>
                                <div class=" col-lg-4 bg-grey">
                                    <div class="p-5 mt-2">
                                        <div class="card-header mt-1">
                                            <h5>Podsumowanie</h5>
                                        </div>
                                        <hr class="my-4">
                                        <div class="row">
                                            <div class="col-6"></div>
                                            <div class="d-flex justify-content-between mb-4">
                                                <h6 class="text-uppercase text-muted">Kwota</h6>
                                                <h6>  @Model.Razem.ToString("C")</h6>
                                            </div>
                                        </div>

                                          @if (Model.ElementyKoszyka != null && Model.ElementyKoszyka.Any())
                                        {
                                            <div class="col-12">
                                                <a asp-controller="FinalizacjaKoszyka" asp-action="Platnosc" class="text-body">
                                                    <button type="button" class="btn btn-dark btn-lg  m-5" style="float:right">
                                                        Zapłać
                                                    </button>

                                                </a>
                                            </div>
                                        }
                                        else
                                        {
                                            
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>